### ISSUE TITLE
qtifw windows

### ISSUE THREAD

**Issue by olear** [olear/natron-linux#17]
make qtifw work in windows.

https://github.com/olear/qtifw/blob/1.5/src/libs/installer/packagemanagergui.cpp

**Comment by olear** [comment]
https://github.com/olear/qtifw/blob/58806909bbab984757d057ae10b1ad5e14a1dd26/doc/installerfw.qdoc#L254

if works, then it's just a matter of making a bat script.

**Comment by MrKepzie** [comment]
So should I try compiling qitfw and set the configuration file ?

**Comment by olear** [comment]
If path with spaces works with a config change then we are good to go, if not then I need to change the source.
