### ISSUE TITLE
Autorun failure if default dir changed

### ISSUE THREAD

**Issue by olear** [olear/natron-linux#18]
Installer fails too launch app after setup if users changes default dir, bug in QTIFW.

**Comment by MrKepzie** [comment]
Also I noticed that when the user clicks uninstall, it removes the whole content of the installation directory instead of only the files that were instead. This is particularly dangerous if the user installed it in, say: the home directory and not in a dedicated “Natron” folder.

**Comment by olear** [comment]
Ok, will try to also find that bug in qtifw.

**Comment by olear** [comment]
Forgot about this one.

Good enough too add check for homedir during uninstall/install? (already checks for rootdir)

The uninstall function is basically QDir::remove, I should add a better function (when I get the time).

Currently debugging the "launch app" failure and windows path issues.

**Comment by crydalch** [comment]
Thanks for looking into the launch app issue, olear!

**Comment by olear** [comment]
There's more that should be fixed in the installer, been mostly occupied with plugins lately, will dedicate time this weekend to fix various installer/Linux issues.
