### ISSUE TITLE
add ffmpeg depends

### ISSUE THREAD

**Issue by olear** [olear/natron-linux#26]
Add depends for ffmpeg, also add an optional build script for an gpl codec pack.

**Comment by MrKepzie** [comment]
I will send you tomorrow the exact configure line for ffmpeg so there is no disparities with the Windows and OSX builds.

**Comment by olear** [comment]
Ok.

**Comment by MrKepzie** [comment]
Got it right here in fact: 

configure \
	--enable-shared \
        --enable-avresample \
        --enable-libmp3lame \
        --enable-libvorbis \
        --enable-libopus \
        --enable-libtheora \
        --enable-libschroedinger \
        --enable-libopenjpeg \
        --enable-libmodplug \
        --enable-libvpx \
        --enable-libspeex \
        --enable-libass \
        --enable-lzma \
        --enable-gnutls \
        --enable-fontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --disable-libxcb \
        --disable-libxcb-shm \
        --disable-libxcb-xfixes \
        --disable-indev=jack \
        --disable-outdev=xv \
        --disable-vda \
        --disable-xlib

**Comment by olear** [comment]
ok, will add depends tomorrow, currently building sdk from scratch on clean install.

**Comment by olear** [comment]
why gnutls?

**Comment by MrKepzie** [comment]
I don’t know this is enabled by default on mac & windows. 
If it’s not needed we can remove this depend

**Comment by olear** [comment]
I guess it enables encrypted streaming or something, but in my opinion adds unneeded libs.
