### ISSUE TITLE
cron job

### ISSUE THREAD

**Issue by olear** [olear/natron-linux#28]
Make a cron job alternative to autobuild.

**Comment by olear** [comment]
Will do some minor adjustments to the uploaded script and update readme.

**Comment by olear** [comment]
Been running the cron job for a day, seems stable.

**Comment by MrKepzie** [comment]
Great, I will start it whenever I get time for it. Is it a daily job ?

**Comment by olear** [comment]
That's up to you, I have it in /retc/cron.hourly, so autobuild2.sh get triggered every hour.
