### ISSUE TITLE
CY2015

### ISSUE THREAD

**Issue by olear** [olear/natron-linux#33]
Be 100% CY2015 compatible. Most is done, just need a complete rebuild and some minor tweaks.

**Comment by olear** [comment]
Can we downgrade boost to 1.55, or just ignore an stay on current version? (in that case 99% compatible :) )

**Comment by MrKepzie** [comment]
I think so because we don’t use any special thing beside boost serialisation and shared ptrs

**Comment by olear** [comment]
Moving to devtoolset 2 (aka GCC 4.8.2) requires CentOS 6.4.

Not an big issue, but CentOS 6.2 and 6.3 will not be supported any more (will probably effect none, 6.2 was not an good release for desktop use etc (I just used the lowest possible version), other distros are unaffected). I checked most VFX/3D software/plugins and their current software requires CentOS/RHEL 6.5(+).

Will do a distro test when done (just started the sdk build on CentOS 6.4).

**Comment by MrKepzie** [comment]
ok keep me updated on that and I will install the appropriate VM on the build server

**Comment by olear** [comment]
The CY2015 SDK tar is done (had to restart due to broken internet connection), will start the Natron build soon.

**Comment by olear** [comment]
Build complete, I didn't notice any regression etc, but will do some more tests.

SDK+binary for testing is available at: https://downloads.natron.fr/~olear/CY2015/

The only "issue" found was that I get a lot of boost warning during build, if this is due to gcc 4.8 or boost downgrade I don't know.

**Comment by olear** [comment]
Tested compatibility against the same distros as with SDK2, all good.

Will merge CY2015 when py2 is ready in Natron.

**Comment by MrKepzie** [comment]
I’m working on it right now, should be done in a few hours

**Comment by MrKepzie** [comment]
Committed, Natron works with Python 2.7 now.  You can merge it

**Comment by olear** [comment]
Nice, will rebuild pyside etc first.

**Comment by olear** [comment]
Done. I uploaded to https://downloads.natron.fr/~olear/CY2015/ at the moment, we should probably add a notice or something on the forum to warn users of changes before replacing existing binaries.

gcc changed to 4.8.2
python changed to 2.7.10
boost changed to 1.55

Will also do some extra tests before replacing existing binaries.

**Comment by MrKepzie** [comment]
I’m right now trying to build python 2.7.10 with mxe (almost done, I have to build bsddb-6.1.26 first).
I’m not sure we should stick to the CY2015 for windows too since everything (almost) is static

**Comment by olear** [comment]
the vfx spec is primarily for Linux, we should/can allow (minor) aberration on the other platforms (but be compatible).
